### ISSUE TITLE
Graphs not loading correctly

### ISSUE THREAD

**Issue by SkylerAusten** [brownplt/LTLTutor#24]
User: sentience-blues

Graphs generated overlapping, and one answer's graph area was blank.

<img width="964" alt="image" src="https://github.com/brownplt/LTLTutor/assets/40815998/fcdf259d-98c0-4749-98ee-e5862c94d7d6">

**Comment by sidprasad** [comment]
Duplicate of https://github.com/brownplt/LTLTutor/issues/13
