### ISSUE TITLE
Errors in trace figures/visualizations 

### ISSUE THREAD

**Issue by LuKuangChen** [brownplt/LTLTutor#29]
The middle figure looks strange.
The bottom-most figure is now shown.

I am using 125.0.3 (64-bit) on a Macbook Pro.

![image](https://github.com/brownplt/LTLTutor/assets/10260693/507c1baf-5338-41b3-8b84-3d1309db0ba5)

**Comment by sidprasad** [comment]
Duplicate of [Is](https://github.com/brownplt/LTLTutor/issues/13
